BPPRC/urls.py
from django.conf.urls.static import settings, static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

handler404 = "extra.views.page_not_found"
handler500 = "extra.views.server_error"

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "admin/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "admin/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("accounts/", include("allauth.urls")),
    path("", include("database.urls")),
    path("", include("bestmatchfinder.urls")),
    path("", include("namingalgorithm.urls")),
    path("", include("clustalanalysis.urls")),
    path("", include("extra.urls")),
    path("", include("graphs.urls")),
    path("", include("association.urls")),
    path("", include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# https://stackoverflow.com/questions/20997863/add-a-prefix-to-url-patterns-in-django
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('database/', include('database.urls')),
#     path('database/', include('bestmatchfinder.urls')),
#     path('database/', include('namingalgorithm.urls')),
#     path('database/', include('clustalanalysis.urls')),
#     path('database/', include('extra.urls')),
#     path('database/', include('graphs.urls')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    path("needle_api", views.needle_api, name="needle_api"),
    path("needle_api_form", views.needle_api_form, name="needle_api_form"),
    path("needle_api_run", views.needle_api_run, name="needle_api_run"),
]

bestmatchfinder/urls.py
from django.contrib import admin
from django.urls import include, path

from bestmatchfinder import views

urlpatterns = [
    path(
        "bestmatchfinder_home/",
        views.bestmatchfinder_home,
        name="bestmatchfinder_home",
    ),
    path(
        "bestmatchfinder_database/",
        views.bestmatchfinder_database,
        name="bestmatchfinder_database",
    ),
    path(
        "run_needle_server/",
        views.run_needle_server,
        name="run_needle_server",
    ),
    path(
        "run_needle_server_celery/",
        views.run_needle_server_celery,
        name="run_needle_server_celery",
    ),
    path(
        "taskstatus_needle_celery/<str:task_id>/",
        views.taskstatus_needle_celery,
        name="taskstatus_needle_celery",
    ),
    path(
        "celery_task_status/<str:task_id>/",
        views.celery_task_status,
        name="celery_task_status",
    ),
    path(
        "bestmatchfinder_database_sequence_run/",
        views.bestmatchfinder_database_sequence_run,
        name="bestmatchfinder_database_sequence_run",
    ),
]

database/urls.py
from django.urls import path

from database import views

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("about/", views.about, name="about"),
    path("funding/", views.about, name="about"),
    path("cite/", views.about, name="about"),
    path("homepage", views.homepage, name="homepage"),
    path("about_page", views.about_page, name="about_page"),
    path("database/", views.database, name="database"),
    path(
        "categorize_database_<str:category>",
        views.categorize_database,
        name="categorize_database",
    ),
    path(
        "search_database_home/",
        views.search_database_home,
        name="search_database_home",
    ),
    path(
        "search_database/",
        views.search_database,
        name="search_database",
    ),
    path("statistics/", views.statistics, name="statistics"),
    path("search_database/add_cart/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:database_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "clear_session_database/",
        views.clear_session_database,
        name="clear_session_database",
    ),
    path("view_cart/", views.view_cart, name="view_cart"),
    path(
        "download_sequences/",
        views.download_sequences,
        name="download_sequences",
    ),
    path(
        "clear_session_user_data/",
        views.clear_session_user_data,
        name="clear_session_user_data",
    ),
    path(
        "user_data_remove/<int:id>/",
        views.user_data_remove,
        name="user_data_remove",
    ),
    path("user_data/", views.user_data, name="user_data"),
    path("cart_value/", views.cart_value, name="cart_value"),
    path("download_data/", views.download_data, name="download_data"),
    path(
        "download_single_sequence/<str:proteinname>/",
        views.download_single_sequence,
        name="download_single_sequence",
    ),
    path(
        "download_category_<str:category>",
        views.download_category,
        name="download_category",
    ),
    path("category_form", views.category_form, name="category_form"),
    path(
        "category_download",
        views.category_download,
        name="category_download",
    ),
    path(
        "threedomain_download",
        views.threedomain_download,
        name="threedomain_download",
    ),
    path(
        "holotype_download",
        views.holotype_download,
        name="holotype_download",
    ),
    path(
        "protein_detail/<slug:name>/",
        views.protein_detail,
        name="protein_detail",
    ),
    path(
        "old_name_new_name/",
        views.old_name_new_name,
        name="old_name_new_name",
    ),
    path(
        "export_old_name_table/",
        views.export_old_name_table,
        name="export_old_name_table",
    ),
    path(
        "export_new_name_table/",
        views.export_new_name_table,
        name="export_new_name_table",
    ),
    path("structures/", views.structures, name="structures"),
    path(
        "structure_pdbid_<str:pdbid>",
        views.structure_pdbid,
        name="structure_pdbid",
    ),
]

bestmatchfinder/forms.py
import tempfile

from Bio import Seq, SeqIO
from crispy_forms.helper import FormHelper
from django import forms

from database.models import PesticidalProteinDatabase

ALLOWED_AMINOACIDS = {
    "E",
    "Q",
    "L",
    "Y",
    "V",
    "W",
    "I",
    "A",
    "H",
    "G",
    "P",
    "S",
    "R",
    "C",
    "T",
    "F",
    "K",
    "N",
    "D",
    "M",
}
# ALLOWED_NUCLEOTIDE = set(IUPACAmbiguousDNA.letters)

# maximum number of query sequences in form
NEEDLE_MAX_NUMBER_SEQ_IN_INPUT = 1

# Error messages
NEEDLE_CORRECT_SEQ_ERROR_MSG = "please paste correct sequence!"
NEEDLE_CORRECT_SEQ_TOO_SHORT_ERROR_MSG = "Too short sequence!"
NEEDLE_SEQUENCE_TYPE = "Currently, protein sequence is allowed"
NEEDLE_CORRECT_SEQ_MAX_SEQ_NUMB_ERROR_MSG = "Too many sequences, maximum is {}".format(NEEDLE_MAX_NUMBER_SEQ_IN_INPUT)


def write_sequence_file(sequence: str):
    """Validate protein sequence"""

    # open a temperorary file
    tmp_seq = tempfile.NamedTemporaryFile(mode="wb+", delete=False)

    # if sequence is none raise the ValidationError
    if len(str(sequence.strip())) == 0:
        raise forms.ValidationError(NEEDLE_CORRECT_SEQ_ERROR_MSG)

    # Write fasta sequence
    if str(sequence).strip()[0] != ">":
        tmp_seq.write(">seq1\n".encode())

    tmp_seq.write(sequence.encode())
    tmp_seq.close()
    # Return name of the temporary file
    return tmp_seq.name


def guess_if_protein(seq, thresh=0.99):
    """Guess if the given sequence is Protein."""
    # protein_letters = ['C', 'D', 'S', 'Q', 'K','I','P','T','F','N','G',
    #                'H','L','R','W','A','V','E','Y','M']
    dna_letters = ["A", "C", "G", "T"]

    for record in SeqIO.parse(seq, "fasta"):
        seq = record.seq

    seq = seq.upper()
    protein_alpha_count = 0
    for letter in dna_letters:
        protein_alpha_count += seq.count(letter)

    return len(seq) == 0 or float(protein_alpha_count) / float(len(seq)) >= thresh


class SequenceForm(forms.Form):
    sequence_in_form = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["sequence_in_form"].label = ""

    def clean_sequence_in_form(self):
        sequence_in_form = self.cleaned_data["sequence_in_form"]

        if sequence_in_form:
            return write_sequence_file(sequence_in_form)
        return sequence_in_form

    def clean(self):
        sequence_in_form = self.cleaned_data["sequence_in_form"]

        if sequence_in_form:
            sequence_is_protein = guess_if_protein(sequence_in_form)

        if not sequence_in_form:
            raise forms.ValidationError("Please paste valid protein sequences")

        if sequence_is_protein:
            raise forms.ValidationError("Currently, it supports only protein sequences")

        return self.cleaned_data


class SearchDatabaseForm(forms.Form):

    protein_id1 = forms.ModelChoiceField(
        queryset=PesticidalProteinDatabase.objects.all(),
        required=False,
        label="Database protein 1",
    )
    sequence1_in_form = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label="Or user-supplied sequence 1 (plain or fasta format)",
    )
    protein_id2 = forms.ModelChoiceField(
        queryset=PesticidalProteinDatabase.objects.all(),
        required=False,
        label="Database protein 2",
    )
    sequence2_in_form = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label="Or user-supplied sequence 2 (plain or fasta format)",
    )
    tool = forms.ChoiceField(
        required=False,
        choices=[("needle", "Needle"), ("blastp", "BLASTP")],
    )

    def clean_sequence1_in_form(self):

        sequence1_in_form = self.cleaned_data["sequence1_in_form"]

        if sequence1_in_form:
            return write_sequence_file(sequence1_in_form)

        return sequence1_in_form

    def clean_sequence2_in_form(self):

        sequence2_in_form = self.cleaned_data["sequence2_in_form"]

        if sequence2_in_form:
            return write_sequence_file(sequence2_in_form)

        return sequence2_in_form

    def clean(self):
        protein1 = self.cleaned_data["protein_id1"]
        protein2 = self.cleaned_data["protein_id2"]
        sequence1_in_form = self.cleaned_data["sequence1_in_form"]
        sequence2_in_form = self.cleaned_data["sequence2_in_form"]

        if sequence1_in_form:
            sequence_is_protein = guess_if_protein(sequence1_in_form)
            if sequence_is_protein:
                raise forms.ValidationError("Currently, it supports only protein sequences")

        if sequence2_in_form:
            sequence_is_protein = guess_if_protein(sequence2_in_form)
            if sequence_is_protein:
                raise forms.ValidationError("Currently, it supports only protein sequences")

        if protein1 and sequence1_in_form:
            raise forms.ValidationError("Please select only one of Sequence / Choice")
        elif not protein1 and not sequence1_in_form:
            raise forms.ValidationError("Please select only one of Sequence / Choice")

        if protein2 and sequence2_in_form:
            raise forms.ValidationError("Please select only one of Sequence / Choice")
        elif not protein2 and not sequence2_in_form:
            raise forms.ValidationError("Please select only one of Sequence / Choice")

        # if not sequence_is_protein1 and not sequence_is_protein2:
        #     raise forms.ValidationError("Currently, it supports only protien sequences")

        return self.cleaned_data

database/templates/newwebpage/best_match_finder.html
{% extends "newwebpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container col-lg-10 pt-5 mt-5 pb-5 mb-5 justify-content-center mx-auto">
  <h1 class="display-4">Search database by sequence</h1>
  <div class="row">
    <div class="container">
  <br>
  <p>Your submitted sequence will be compared to all publicly available sequences in the database using the Needle algorithm to find the best overall matches.</p>
  <p> Paste amino acid sequence (in plain or fasta format) into the box below</p>
>Name
<br>
MDNNPNINECIPYNCLSNPEVEVLGGERIETGYTPIDISLSLTQFL ...
<br>
<br>

  <b><strong> Query sequence&nbsp;</strong></b> <div class="d-inline-block text-right w-50"> <a href="#" class="example-sequence-button text-md-left">Use example sequence</a></div>
  <form action="{% url 'run_needle_server_celery' %}" method="post">
    {% csrf_token %}
    {{ form |crispy }}
    <button type="submit" class="btn btn-primary"  >Submit</button>
    <input class="btn btn-primary"  type="reset" value="Clear">
  </form>

</div>
</div>
</div>

{% endblock content %}

{% block extrajs %}

<script type="text/javascript" src="{% static 'database/js/chosen.jquery.min.js' %}"> </script>

<script>
  var str = ' >WP_132352567.1 alpha-xenorhabdolysin family binary toxin subunit A [Photorhabdus khanii]\nMEKYMLLAQFPAEKTLNETDIPSATLQLLTGKQAGVARPGGIFTKEDLINIKLYVKKGLSLPFNLEEVKNYLGYQRVDIPGLEPEDIHILFEEIRTHSLSWSGVENDIMQQSMDLEIVGKQITETGGNIISIINEMPIIERIKKKLGELSDRQLASITYTNEDKEVSYALEEILDNMKNDIQKQQRKTEKVKTEVSDFKLKLIGGRLSNGGIAFGLQPQVENKRKLMKDNKMSVNIKDLDDKITEKKTEIIQLKQDYDKFVGLAFSGIVGGLIGLAITGGIFGAKAEEVRKRKNTLIEEVRGLEESIKGKRALQESMASLSIDFSDIDTRLLDAEVALNHLDYMWQSMLT QINASRDKFAEINDALKLTSFITKFQQVISPWKDVEGSAKQLVKVFDEALKEYKQRYN ';
  console.log(str);
  $(document).ready(function() {
    $('.example-sequence-button').click(function() {
      $('#id_sequence_in_form').val(str);
    })
  });

</script>
{% endblock %}

database/templates/newwebpage/best_match_finder_database.html
{% extends "newwebpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}


<div class="container col-lg-12 pt-5 mt-5 pb-5 mb-5 justify-content-center mx-auto visible">
<div class="col-lg-12 pt-5 mt-5 pt-b mb-5 mx-auto">
    <h2 class="display-4">Compare two proteins - from database or user-supplied</h2>
  <br>
  <form action="/bestmatchfinder_database_sequence_run/" method="post">
    {% csrf_token %}
    {{ form |crispy }}
    <button type="submit" class="btn btn-primary"  >Submit</button>
  </form>
</div>
</div>


{% endblock content %}

{% block extrajs %}

<script type="text/javascript" src="{% static 'database/js/chosen.jquery.min.js' %}"> </script>

<script>
  $(document).ready(function() {
    $('#id_protein_id1').chosen();
    $('#id_protein_id2').chosen();
  });

</script>
{% endblock %}

database/templates/newwebpage/dendogram_homepage.html
{% extends "newwebpage/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">  <!-- singular -->
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}
</br>
</br>
</br>
</br></br>
</br>
{% block content %}

<h5>To analyse particular proteins/domains first select them using the <a href="{% url 'search_database_home' %}">Database/Search facility</a> and then go to the cart page</h5>
</br>
</br>
<h2>Create a dendrogram from selected protein classes</h2>
</br>
</br>
<div>
  {% crispy form %}

  {% if form.errors %}
     {% for field in form %}
        {% for error in field.errors %}
            {{ error|escape }}
        {% endfor %}
     {% endfor %}
  {% endif %}

</div>
</br>
</br>
</br>
</br>

{% for description in descriptions %}
<div>
		<p <a class="text-left font-weight-bold">{{description.name}}:</a> <span class="font-weight-light"> {{description.description}} </span> </p>
</div>
{% endfor %}


{% endblock content %}

{% block extrahead %}
<style>

label {
    width:80px;
    clear:left;
    text-align:left;
    padding-right:2px;
}

input, label {
    float:left;
}
</style>
{% endblock extrahead %}

{% block extrajs %}
<script>
  $(function() {
    $('.form-check').css('display', 'inline-block');
  })();
</script>

{% endblock extrajs %}

database/templates/newwebpage/download_form.html
{% extends "newwebpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}
<section>
<div class="col-lg-12 pt-5 mt-5 pt-b mb-5 mx-auto">
<div class="container">
<h3> Click the boxes below to download all the proteins in the specified class(es).</h3>
</br>
{% crispy form1 %}
</div>
</div>

<div class="container">
<div>
<h3> Download all the 3-domain sequences </h3>
</br>
{% crispy form2 %}
</br>
</div>
</div>

<div class="container">
<div>
  </br>
<h3> Download all the holotype sequences </h3>
</br>
{% crispy form3 %}
</div>
</div>

</section>
<div class="lead">
  <h4>
		Individual proteins can be added to the Cart via <a href="/search_database_home/">Search page </a> or via clicking in the above icons. Proteins in the Cart can be supplemented with your own sequences and then either downloaded or sent for analysis.
	</h4>
</div>
</div>
</br>

{% endblock content %}

{% block extrahead %}
<style>

.form-check {
  font-size: 16px;
  line-height: 2;
}
</style>

{% endblock extrahead %}


{% block extrajs %}
<script>
$('input[type=checkbox]').click((e) => {
  const form = $(e.target).closest('form');
  if ($(e.target).val() === 'all') {
    const checkAll = $(e.target).prop('checked');
    form.find('input[type=checkbox]').prop('checked', checkAll);
  } else {
    if (form.find('input[type=checkbox]:not([value=all]):not(:checked)').length === 0) {
      form.find('input[type=checkbox][value=all]').prop('checked', true);
    } else {
      form.find('input[type=checkbox][value=all]').prop('checked', false);
    }
  }
  if ($(e.target).val() === 'full_length') {
    const checkAll = $(e.target).prop('checked');
    form.find('input[type=checkbox]').prop('checked');
  } else {
    if (form.find('input[type=checkbox]:not([value=full_length]):not(:checked)').length === 0) {
      form.find('input[type=checkbox][value=full_length]').prop('checked', true);
    } else {
      form.find('input[type=checkbox][value=full_length]').prop('checked', false);
    }
  }

});
</script>

{% endblock extrajs %}

database/templates/newwebpage/front-page.html
{% load static %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

  <div class="container">
    <div class="row">
      <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center" data-aos="fade-left" data-aos-delay="200">
        <a><img src="{% static 'assets/img/bpprc.png' %}" alt="Responsive image" class="img-fluid" ></a>
        <h1 data-aos="fade-up" data-aos-delay="400">Welcome to the Bacterial Pesticidal Protein Database</h1>
        <div data-aos="fade-up" data-aos-delay="800">
        <a href="#about" class="btn-get-started scrollto">About Us</a>
      </div>
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="fade-left" data-aos-delay="200">
        <img src="{% static 'assets/img/protein.png' %}" class="img-fluid" alt="">
      </div>
    </div>
  </div>

</section><!-- End Hero -->

database/templates/newwebpage/links.html
{% extends "newwebpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<!-- ======= F.A.Q Section ======= -->
<div class="col-lg-12 pt-5 mt-5 pt-b mb-5 mx-auto">
<section id="faq" class="faq">
  <div class="container">

    <div class="section-title" data-aos="fade-up">
      <h2>Links</h2>
    </div>

    <div class="row d-flex" data-aos="fade-up" >
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Link</th>
            <th scope="col">Description</th>
          </tr>
        </thead>
      {% for link in links %}
      <tbody>
        <tr>
          <td>{{ link.name }}</td>
          <td> <a target="_blank" href="{{ link.link }}">Link</a></td>
          <td>{{ link.description  }}</td>
        </tr>
      </tbody>
      {% endfor %}
      </table>
    </div><!-- End F.A.Q Item-->
  </div>
</section><!-- End F.A.Q Section -->
</div>
{% endblock content %}

database/templates/newwebpage/logo.html
{% load static %}

<!-- ======= Clients Section ======= -->
<section id="clients" class="clients clients clients clients">
  <div class="container">

    <div class="row">

      <div class="col-lg-2 col-md-4 col-6">
        <a target="_blank" href="http://www.sussex.ac.uk/lifesci/">
        <img src="{% static 'assets/img/clients/US.png' %}" class="img-fluid" alt="" data-aos="zoom-in">
        </a>
      </div>

      <div class="ml-3 mr-3 col-lg-2 col-md-4 col-6">
        <a target="_blank" href="https://www.cardiff.ac.uk/biosciences">

        <img src="{% static 'assets/img/clients/CU.png' %}" class="img-fluid" alt="" data-aos="zoom-in" data-aos-delay="100">
        </a>
      </div>

      <div class="ml-3 mr-3 col-lg-2 col-md-4 col-6">
        <a target="_blank" href="http://entnemdept.ufl.edu/">
        <img src="{% static 'assets/img/clients/UF.png' %}" class="img-fluid" alt="" data-aos="zoom-in" data-aos-delay="200">
        </a>
      </div>

      <div class="ml-3 mr-3 col-lg-2 col-md-4 col-6 logos">
        <a target="_blank" href="https://www.iucrc-camtech.org/">
        <img src="{% static 'assets/img/clients/camtech.png' %}" class="img-fluid" alt="" data-aos="zoom-in" data-aos-delay="300">
        </a>
      </div>

      <div class="ml-3 mr-3 col-lg-2 col-md-4 col-6 logos">
        <a target="_blank" href="https://www.nsf.gov/">
        <img src="{% static 'assets/img/clients/NSF.png' %}" class="img-fluid" alt="" data-aos="zoom-in" data-aos-delay="400">
        </a>
      </div>


    </div>

  </div>
</section><!-- End Clients Section -->

database/templates/newwebpage/naming_home.html
{% extends "newwebpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="app-container col-lg-10 pt-5 mt-5 justify-content-center mx-auto">
<div class="col-lg-10 pt-5 mt-5 pt-b mb-5 mx-auto">

  <b><strong><h2>Naming Algorithm &nbsp;</h2></strong></b>

  <form action="{% url 'run_naming_algorithm' %}" method="post">
    {% csrf_token %}
    <textarea name="fulltextarea" placeholder="Paste fasta sequence" rows="15" cols="80"></textarea>
    <br></br>
    <input type="submit" value="Submit!"/>

  </form>

</div>
</div>

{% endblock content %}

database/templates/newwebpage/navbar.html
{% load static %}

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="/homepage"><span>Home</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
      </div>

      <nav class="nav-menu d-none d-lg-block mr-auto">
        <ul>
          <li class="drop-down"><a>About</a>
            <ul>
              <li><a href="/about/">About Us</a></li>
              <li><a href="/funding/">Funding</a></li>
              <li><a href="/cite/">Cite</a></li>
            </ul>
          </li>
          <li class="drop-down"><a>Database</a>
            <ul>
              <li><a href="/database/">Structural Classes</a></li>
              <li><a href="/search_database_home/">Search by Name</a></li>
              <li><a href="/structures/">Protein Structures</a></li>
              <li><a href="/category_form">Download</a></li>
            </ul>
          </li>
          <li class="drop-down"><a>BestMatchFinder</a>
            <ul>
              <li><a href="/bestmatchfinder_home/">Search by sequence</a></li>
              <li><a href="/bestmatchfinder_database/">Pairwise comparision</a></li>
            </ul>
          </li>
          <li class="drop-down"><a>Submit your sequence for naming</a>
            <ul>
              <li><a href="/submit/">Submission form</a></li>
            </ul>
          </li>
          <li class="drop-down"><a>Links</a>
            <ul>
              <li><a href="/links/">Links</a></li>
            </ul>
          </li>
          <li class="drop-down"><a>FAQs</a>
            <ul>
              <li><a href="/faq/">Frequently asked questions</a></li>
              <li><a href="/tutorial/">How to use this site?</a></li>
            </ul>
          </li>
          <li class="drop-down"><a>Feedback</a>
            <ul>
              <li><a href="/feedback_home">Feedback form</a></li>
            </ul>
          </li>
          <li class="drop-down"><a>Cart</a>
            <ul>
              <li><a href="/view_cart">Download or analyse specific sequences</a></li>
            </ul>
          </li>
        </ul>
      </nav><!-- .nav-menu -->
      <!-- <nav class="nav-menu d-none d-lg-block">
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'account_logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
          <li><a href="{% url 'account_login' %}">Login</a></li>
          {% endif %}
        </ul>
      <nav> -->
</div>
  </header><!-- End Header -->

database/templates/newwebpage/view.html
{% extends "newwebpage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="app-container col-lg-10 pt-5 mt-5 justify-content-center mx-auto">
  <div class="col-lg-10 pt-5 mt-5 pt-b mb-5 mx-auto">

    <b><strong><p> Your sequence has successfully been submitted to the naming committee. &nbsp;</p> </strong></b>
    <b><strong><p>You will be contacted shortly. &nbsp;</p> </strong></b>

  </div>
</div>

{% endblock content %}