BPPRC/urls.py
from django.conf.urls.static import settings, static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

handler404 = "extra.views.page_not_found"
handler500 = "extra.views.server_error"

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "admin/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "admin/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("accounts/", include("allauth.urls")),
    path("", include("database.urls")),
    path("", include("bestmatchfinder.urls")),
    path("", include("namingalgorithm.urls")),
    path("", include("clustalanalysis.urls")),
    path("", include("extra.urls")),
    path("", include("graphs.urls")),
    path("", include("association.urls")),
    path("", include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# https://stackoverflow.com/questions/20997863/add-a-prefix-to-url-patterns-in-django
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('database/', include('database.urls')),
#     path('database/', include('bestmatchfinder.urls')),
#     path('database/', include('namingalgorithm.urls')),
#     path('database/', include('clustalanalysis.urls')),
#     path('database/', include('extra.urls')),
#     path('database/', include('graphs.urls')),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    path("needle_api", views.needle_api, name="needle_api"),
    path("needle_api_form", views.needle_api_form, name="needle_api_form"),
    path("needle_api_run", views.needle_api_run, name="needle_api_run"),
]

database/urls.py
from django.urls import path

from database import views

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("about/", views.about, name="about"),
    path("funding/", views.about, name="about"),
    path("cite/", views.about, name="about"),
    path("homepage", views.homepage, name="homepage"),
    path("about_page", views.about_page, name="about_page"),
    path("database/", views.database, name="database"),
    path(
        "categorize_database_<str:category>",
        views.categorize_database,
        name="categorize_database",
    ),
    path(
        "search_database_home/",
        views.search_database_home,
        name="search_database_home",
    ),
    path(
        "search_database/",
        views.search_database,
        name="search_database",
    ),
    path("statistics/", views.statistics, name="statistics"),
    path("search_database/add_cart/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:database_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "clear_session_database/",
        views.clear_session_database,
        name="clear_session_database",
    ),
    path("view_cart/", views.view_cart, name="view_cart"),
    path(
        "download_sequences/",
        views.download_sequences,
        name="download_sequences",
    ),
    path(
        "clear_session_user_data/",
        views.clear_session_user_data,
        name="clear_session_user_data",
    ),
    path(
        "user_data_remove/<int:id>/",
        views.user_data_remove,
        name="user_data_remove",
    ),
    path("user_data/", views.user_data, name="user_data"),
    path("cart_value/", views.cart_value, name="cart_value"),
    path("download_data/", views.download_data, name="download_data"),
    path(
        "download_single_sequence/<str:proteinname>/",
        views.download_single_sequence,
        name="download_single_sequence",
    ),
    path(
        "download_category_<str:category>",
        views.download_category,
        name="download_category",
    ),
    path("category_form", views.category_form, name="category_form"),
    path(
        "category_download",
        views.category_download,
        name="category_download",
    ),
    path(
        "threedomain_download",
        views.threedomain_download,
        name="threedomain_download",
    ),
    path(
        "holotype_download",
        views.holotype_download,
        name="holotype_download",
    ),
    path(
        "protein_detail/<slug:name>/",
        views.protein_detail,
        name="protein_detail",
    ),
    path(
        "old_name_new_name/",
        views.old_name_new_name,
        name="old_name_new_name",
    ),
    path(
        "export_old_name_table/",
        views.export_old_name_table,
        name="export_old_name_table",
    ),
    path(
        "export_new_name_table/",
        views.export_new_name_table,
        name="export_new_name_table",
    ),
    path("structures/", views.structures, name="structures"),
    path(
        "structure_pdbid_<str:pdbid>",
        views.structure_pdbid,
        name="structure_pdbid",
    ),
]

namingalgorithm/urls.py
from django.urls import path

from namingalgorithm import views

urlpatterns = [
    # path('', views.send_mail, name='sendmail'),
    path("admin/contact/", views.contact_email, name="contact"),
    path("admin/success/", views.success_email, name="success"),
    path("submit_home/", views.submit_home, name="submit_home"),
    path("submit/", views.submit, name="submit"),
    path(
        "naming_algorithm/",
        views.naming_algorithm,
        name="naming_algorithm",
    ),
    path(
        "run_naming_algorithm/",
        views.run_naming_algorithm,
        name="run_naming_algorithm",
    ),
    path("run_align/", views.run_align, name="run_align"),
    path("align_results/", views.align_results, name="align_results"),
    # path('clone_user_submission/', views.cloneUserSubmission,
    #      name='clone_user_submission')
]

database/models.py
""" """

import re
import textwrap

from Bio.SeqUtils.ProtParam import ProteinAnalysis
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.core.files.base import ContentFile
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from database.storage import OverwriteStorage

TRUE_FALSE_CHOICES = ((True, "Yes"), (False, "No"))


class OldnameNewnameTableLeft(models.Model):
    """
    Class representing a Old Name and New name Table.
    Organized by New Name.
    """

    # 2020 Nomenclature based names i.e. New Name of the proteins
    name_2020 = models.CharField(max_length=250, blank=True, null=True)

    # 1998 Nomenclature based names i.e. Old Name of the proteins
    name_1998 = models.CharField(max_length=250, blank=True, null=True)

    # Several different names of the same protein mentioned in the literature by various authors i.e. multiple names for the protein
    # Specially before the Nomenclature system (1998)
    alternative_name = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Organized by new name"
        verbose_name_plural = "Organized by new name"


class OldnameNewnameTableRight(models.Model):
    """
    Class representing a Old Name and New name Table.
    Organized by Old Name.
    """

    # 1998 Nomenclature based names i.e. Old Name of the proteins
    name_1998 = models.CharField(max_length=250, blank=True, null=True)

    # 2020 Nomenclature based names i.e. New Name of the proteins
    name_2020 = models.CharField(max_length=250, blank=True, null=True)

    # Several different names of the same protein mentioned
    # in the literature by various authors i.e. multiple
    # names for the protein
    # Specially before the Nomenclature system (1998)
    alternative_name = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Organized by Oldname"
        verbose_name_plural = "Organized by Oldname"


CHOICES = [
    ("yes", "Yes"),
    ("no", "No"),
]


class StructureDatabase(models.Model):
    """
    Structure database fields. The data is curated by Prof.Colin Berry.
    """

    # 2020 Nomenclature based names i.e. New Name of the proteins
    name = models.CharField(max_length=25, blank=True, null=True)

    # 1998 Nomenclature based names i.e. Old Name of the proteins
    oldname = models.CharField(max_length=75, blank=True, null=True)

    # National Center for Biotechnology Information (NCBI) accession number
    # https://www.ncbi.nlm.nih.gov/genbank/sequenceids/
    # https://www.ncbi.nlm.nih.gov/genbank/acc_prefix/
    accession = models.CharField(max_length=75, blank=True, null=True)

    # Protein Data Bank identifier
    # https://proteopedia.org/wiki/index.php/PDB_code
    # https://www.rcsb.org/pages/about-us/index
    pdbid = ArrayField(models.CharField(
        max_length=1000, null=True), default=list)

    # NCBI PubMed id
    # https://www.ncbi.nlm.nih.gov/pmc/pmctopmid/
    doi = models.TextField(null=True, blank=True)
    pubmedid = models.CharField(max_length=75, blank=True, null=True)

    # PDB id released year
    year = models.CharField(max_length=5, blank=True, null=True)

    # This field provides whether the protein sequence is modified or not
    # If modified "Yes" otherwise "No"
    modified = models.CharField(
        max_length=100, choices=CHOICES, default="Yes", blank=True, null=True)

    # Any other information related to the protein
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Structure Information"
        verbose_name_plural = "Structure Database"


class PesticidalProteinHiddenSequence(models.Model):
    """
    Here’s a list of toxins that would be useful to add to the naming analysis as extra hidden seqs so that we get extra data for those sequences that don’t have good matches.  I’ve only put in one example each for TcA/B/C but that should be enough to show us if we have a match.  I’m afraid I don’t have accession numbers of most of these.
    """

    name = models.CharField(max_length=15, blank=True, null=True)
    oldname = models.CharField(max_length=305, blank=True, null=True)
    othernames = models.TextField(blank=True, null=True)
    accession = models.CharField(max_length=25, blank=True, null=True)
    year = models.CharField(max_length=5, blank=True, null=True)
    sequence = models.TextField(null=True)
    bacterium = models.BooleanField(
        default=True, choices=TRUE_FALSE_CHOICES, blank=True, null=True)
    bacterium_textbox = models.CharField(
        max_length=250, default="Bacillus Thuringiensis", blank=True, null=True)
    strain = models.CharField(max_length=250, blank=True, null=True)
    publication = models.TextField(null=True, blank=True)
    family = models.CharField(
        max_length=305, blank=True, null=True, default="None")
    toxicto = models.CharField(
        max_length=250, blank=True, null=True, default="None")
    nontoxic = models.CharField(max_length=250, blank=True, null=True)
    mammalian_active = models.CharField(
        max_length=250, blank=True, null=True)

    # Protein Data Bank identifier
    # https://proteopedia.org/wiki/index.php/PDB_code
    # https://www.rcsb.org/pages/about-us/index
    pdbcode = models.CharField(max_length=10, blank=True, null=True)
    comment = models.TextField(null=True, blank=True)
    submittersname = models.CharField(max_length=25, blank=True, null=True)
    submittersemail = models.EmailField(
        max_length=70, blank=True, null=True)
    taxonid = models.CharField(max_length=25, validators=[RegexValidator(
        r'\d{25}', 'Number must digits', 'Invalid number')], blank=True, null=True)
    partnerprotein = models.BooleanField(
        default=True, choices=TRUE_FALSE_CHOICES, blank=True, null=True)
    partnerprotein_textbox = models.CharField(
        max_length=250, blank=True, null=True)
    dnasequence = models.TextField(blank=True, null=True)
    uploaded = models.DateTimeField(
        "Uploaded", default=timezone.now, blank=True, null=True)
    alignresults = models.TextField(null=True, blank=True)
    predict_name = models.TextField(null=True, blank=True)
    terms_conditions = models.BooleanField(
        default=False, choices=TRUE_FALSE_CHOICES, blank=True, null=True)
    admin_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    admin_comments = models.TextField(null=True, blank=True)
    public = models.BooleanField(default=False, blank=True, null=True)
    # private = models.BooleanField(
    #     default=True, choices=TRUE_FALSE_CHOICES, blank=True, null=True)
    fastasequence_file = models.FileField(
        upload_to="fastasequence_files/", null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Hidden sequence"
        verbose_name_plural = "Hidden sequences for naming purpose"


class PesticidalProteinPrivateDatabase(models.Model):
    """
    Private sequences are used only for the naming purpose. These protein sequences are unreleased to public. Once NCBI release's the sequence and the sequences are moved to public model.
    """

    # User who submits the sequence through "sequence submit form"
    submittersname = models.CharField(max_length=25, blank=True, null=True)

    # User corresponding email
    submittersemail = models.EmailField(max_length=70, blank=True, null=True)

    # 2020 Nomenclature New Name
    name = models.CharField(max_length=15, null=True,
                            verbose_name="Protein Name")

    # Protein sequence
    sequence = models.TextField(null=True, verbose_name="Protein Sequence")

    # Is it a bacterium sequence?. If the choice is "yes" then name of the
    # bacteria should be in the bacterium textbox. If the choice is "no" then explanation about the source.
    # Note: The BPPRC doesn't normally assign names to proteins that are not
    # of bacterial origin. If user wish to make a special case for the
    # sequence, the explanation can be stored in the text box.
    bacterium = models.BooleanField(
        default=True, choices=TRUE_FALSE_CHOICES, blank=True, null=True)
    bacterium_textbox = models.CharField(max_length=250, blank=True, null=True)

    # NCBI taxon id
    # https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi
    taxonid = models.CharField(max_length=25, validators=[RegexValidator(
        r'\d{25}', 'Number must digits', 'Invalid number')], blank=True, null=True)

    # Submission year
    year = models.CharField(max_length=5, null=True)

    # National Center for Biotechnology Information (NCBI) accession number
    # https://www.ncbi.nlm.nih.gov/genbank/sequenceids/
    # https://www.ncbi.nlm.nih.gov/genbank/acc_prefix/
    accession = models.CharField(
        max_length=25, null=True, verbose_name="NCBI accession number")

    # Partner protein required for toxicity?. If the choice is "yes", then
    # user can mention name of the protein
    partnerprotein = models.BooleanField(
        default=True, choices=TRUE_FALSE_CHOICES, blank=True, null=True)
    partnerprotein_textbox = models.CharField(
        max_length=250, blank=True, null=True)

    # If toxic to the organism. User can mention the name.
    toxicto = models.CharField(max_length=250, blank=True, null=True)

    # If nontoxic to the organism. User can mention the name.
    nontoxic = models.CharField(max_length=250, blank=True, null=True)

    # Correponding DNA sequence information
    dnasequence = models.TextField(blank=True, null=True)

    # Protein Data Bank identifier

database/templates/namingalgorithm/email.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<h3> Email</h3>


  {% crispy form %}

{% endblock content %}



{% block extrajs %}
<script>

subName=localStorage.getItem('submittersname');
subEmail=localStorage.getItem('email');
subname=localStorage.getItem('name');

if (subName) {
    document.getElementById("id_submittersname").value = subName;
    document.getElementById("id_subemail").value = subEmail;
    document.getElementById("id_name").value = subname;
    localStorage.clear()
  }

</script>

{% endblock extrajs %}

database/templates/namingalgorithm/email_success.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <b><strong><p> Your email sent to {{ submittersemail }}. A saved copy in the Send Email admin. &nbsp;</p> </strong></b>

  </br>
  </br>
  <a href="{% url 'admin:index' %}">Return to admin panel</a>




{% endblock content %}

database/templates/namingalgorithm/feedback_home.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- in header block -->
{% include "feedback/header.html" %}

<!-- in body block -->
{% include "feedback/button.html" %}

database/templates/namingalgorithm/naming_home.html
{% extends "base.html" %}
{% block content %}
{% load static %}

  <b><strong><h2>Naming Algorithm &nbsp;</h2></strong></b>

  <form action="{% url 'run_naming_algorithm' %}" method="post">
    {% csrf_token %}
    <textarea name="fulltextarea" placeholder="Paste fasta sequence" rows="15" cols="80"></textarea>
    <br></br>
    <input type="submit" value="Submit!"/>

  </form>

{% endblock content %}

database/templates/namingalgorithm/naming_results.html
{% extends "base.html" %}
{% block content %}
{% load static %}


  <body>
  <td class="pgm_list" width="100%"><h2>Naming Algorithm </h2></td>
  <br>
  </body>
  </html>

  <form action="{% url 'naming_algorithm' %}" method="post">
    {% csrf_token %}
    <br>
    <br>
    <h4> The predicted name of the sequence: {{ context.predicted_name }} </h4> <br>
    <h4> Do you want to add the predicted name {{ context.predicted_name }} to the database ? </h4> <br>
    <h4>The percentage identity {{ context.percentage_identity }} to the database sequence </h4> <br>
    <input type="submit" name="{{ context.predicted_name }}" value="Yes"> &nbsp &nbsp &nbsp
    <input type="submit" name="No" value="No">
    <br>
  </form>
</head>

{% endblock content %}

database/templates/namingalgorithm/needle.html
{% extends "base.html" %}

{% block content %}

        <!DOCTYPE html>
        <html>
        <head>
        <style>
        table, th, td {
          border: 1px solid black;
        }
        </style>
        </head>
        <body>

        <br></br>
        <h2> <pre>Category: {{ category }} </pre> </h2>
        <br></br>
        <h2><pre>Predicted name: {{ predicted_name }} </pre> </h2>
        <br></br>
        <h2> <pre>Best Match Found: {{ name }} </pre> </h2>
        <br></br>
        <pre>Alignment : {{ align }} </pre>

{% endblock content %}

database/templates/namingalgorithm/submit_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


  <h1 class="text-center list-unstyled"> <ul> Naming</h1>
  <br>
  <br>
  <br>
  <h3> Proteins will only get a name if they are derived from a bacterium and satisfies one of the criteria </h3>
  <br>
  <h5> <li> Have >95% identity to an existing named protein (or)</li> </h5>
  <h5> <li> Have demonstrated activity against a target pest organism</li></ul> </h5>
  <br>
  <br>

  <form action="{% url 'submit' %}" method="POST">
    {% csrf_token %}
    {{ formset.management_form }}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="id_submittersname">Submitters Name</label>
      <input type="text" name="submittersname" class="form-control" id="id_submittersname" placeholder="Nancy Sanders">
    </div>
    <div class="form-group col-md-6">
      <label for="id_submittersemail">Submitters Email</label>
      <input type="text" name="submittersemail" class="form-control" id="id_submittersemail" placeholder="Email">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-10">
      <label for="id_name">Current Protein Name</label>
      <input type="text" name="name" class="form-control" id="id_name" placeholder="CryE1">
    </div>
    <div class="form-group col-md-2">
      <label for="id_year">Year</label>
      <input type="text" name="year" class="form-control" id="id_year" placeholder="2020">
    </div>
</div>
  <div class="form-row">
    <div class="form-group col-md-1">
      <label for="id_bacterium_0" class="col-form-label  requiredField">
                Bacterium<span class="asteriskField">*</span> </label>
      <label for="id_id_bacterium_0_1">Yes</label>
      <input type="radio" name="bacterium" id="id_id_bacterium_0_1" value="True">

      <label for="id_id_bacterium_0_2">No</label>
      <input type="radio"  name="bacterium" id="id_id_bacterium_0_2" value="False">
    </div>
    <div div="div_id_bacterium_textbox" class="form-group col-md-6">
      <label for="id_bacterium_textbox">Bacterium Name</label>
      <div>
      <input type="text" class="form-control" id="id_bacterium_textbox">
    </div>
    </div>
    <div id="div_id_taxonid" class="form-group col-md-4">
      <label for="id_taxonid">Taxonid</label>
      <div>
      <input type="text" class="form-control" id="id_taxonid">
    </div>
    </div>
  </div>
<div class="form-row">
  <div id="div_id_accession" class="form-group col-md-4">
    <label for="id_accession">Accession Number</label>
    <input type="text" class="form-control" id="id_accession" placeholder="046395991">
  </div>
</div>
<div id="div_id_dnasequence" class="form-group">
  <label for="id_dnasequence">DNA Sequence</label> </br>
  <textarea name="dnasequence" cols="100" rows="10"> </textarea>
</div>
<div id="div_id_proteinsequence" class="form-group">
  <label for="id_proteinsequence">Protein Sequence</label> </br>
  <textarea name="proteinsequence" cols="100" rows="10"> </textarea>
</div>
<div class="form-row">
  <div class="form-group col-md-6">
    <label for="inputCity">Partner Protein Name</label>
    <input type="text" class="form-control" id="inputCity">
  </div>
</div>
<input type="hidden" id="id_toxicto-TOTAL_FORMS" value=1 />
<div id="div_id_toxicto" class="form-group dynamic-rows">
  <label for="id_toxicto">Toxic to</label>
  <div class="input-group">
  <input type="text" class="form-control" id="id_toxicto" placeholder="" name="toxicto">
  <div class="input-group-append">
    <button class="btn btn-success add-form-row">+</button>
  </div>
  </div>
</div>
<div class="form-group">
  <label for="inputAddress2">PDB Code</label>
  <input type="text" class="form-control" id="inputAddress2" placeholder="5KUC">
</div>
<div class="form-group">
  <label for="inputAddress2">Publication</label> </br>
  <textarea name="dnasequence" cols="100" rows="10"> </textarea>
</div>
<div class="form-group">
  <label for="inputAddress2">Comments</label> </br>
  <textarea name="dnasequence" cols="100" rows="10"> </textarea>
</div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock content %}

{% block extrahead %}
<style>

textarea {
  width: 100%;
}

</style>
{% endblock extrahead %}


{% block extrajs %}
<script>
$(function() {
  $('#div_id_taxonid').append("<a href='https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi' target='_blank'> Where can I find taxonid?</a>")
});
</script>


<script>
$(function() {
    $('input[name="sourcebacterium"]').change(function(obj) {
    console.log($(this).val());
    if ($(this).val() === 'True') {
        $('#id_sourcebacterium_textbox').parent().parent().show();
    } else {
      $('#id_sourcebacterium_textbox').parent().parent().hide();
    }
  });
  $('#id_sourcebacterium_textbox').parent().parent().hide();
});
</script>

<script>
$(function() {
    $('input[name="bacterium"]').change(function(obj) {
    console.log($(this).val());
    if ($(this).val() === 'True') {
        $('#id_bacterium_textbox').parent().parent().show();
        $('#id_taxonid').parent().parent().show();
    } else {
      $('#id_bacterium_textbox').parent().parent().show();
      $('#id_taxonid').parent().parent().hide();
      swal("The BPPRC does not normally assign names to proteins that are not of bacterial origin.  If you wish to make a special case for your sequence, please explain in the Comments box below!");
    }
  });
  $('#id_bacterium_textbox').parent().parent().show();
  $('#id_taxonid').parent().parent().hide();
});
</script>


<script>
$(function() {
    $('input[name="partnerprotein"]').change(function(obj) {
    console.log($(this).val());
    if ($(this).val() === 'True') {
        $('#id_partnerprotein_textbox').parent().parent().show();
    } else {
      $('#id_partnerprotein_textbox').parent().parent().hide();
    }
  });
  $('#id_partnerprotein_textbox').parent().parent().hide();
});
</script>

<script type="text/javascript">

  $('.js-captcha-refresh').click(function (evt) {
      evt.preventDefault();
      $.getJSON("/captcha/refresh/", function (result) {
          $('.captcha').attr('src', result['image_url']);
          $('#id_captcha_0').val(result['key'])
      });
  });


  $(function() {
    $('.form-check').css('display', 'inline-block');
  });

</script>


<script type='text/javascript'>
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
    newElement.find('input').each(function() {
        var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
    });
    newElement.find('label').each(function() {
        var forValue = $(this).attr('for');
        if (forValue) {
          forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
          $(this).attr({'for': forValue});
        }
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    var conditionRow = $('.dynamic-rows:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('<i class="fa fa-minus"></i>');
    return false;
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.dynamic-rows').remove();
        var forms = $('.dynamic-rows');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '.add-form-row', function(e){
    e.preventDefault();
    cloneMore('.dynamic-rows:last', 'toxicto');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('toxicto', $(this));
    return false;
});
</script>


{% endblock %}

database/templates/namingalgorithm/view.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <b><strong><p> Your sequence has successfully been submitted to the naming committee. &nbsp;</p> </strong></b>
    <b><strong><p>You will be contacted shortly. &nbsp;</p> </strong></b>



{% endblock content %}